### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by vd2309** [epnev/continuous_time_ca_sampler#6]
Hi @epnev !

What we are doing now is updating the temporal components on the first iteration with constrained foopsi and running the second iteration with MCMC, as recommended in the paper.  But when I do this I get this error:

Error using get_next_spikes (line 66)
Error: File: /Users/axel/Desktop/ca_source_extraction-master/removeSpike.m Line: 46 Column: 1
The input character is not valid in MATLAB statements or expressions.

Error in cont_ca_sampler (line 238)
    [spiketimes, ~]  = get_next_spikes(spiketimes_(:)',A_*Gs',Ym',ef,tau,sg_^2, rate,
    std_move, add_move, Dt, A_);

Error in update_temporal_components (line 205)
            parfor jj = 1:length(O{jo})

Please let me know how to proceed. 

Thank you very much,
Ginny

**Comment by epnev** [comment]
@vd2309  This is weird. The [removeSpike.m](https://github.com/epnev/continuous_time_ca_sampler/blob/master/utilities/removeSpike.m) function doesn't even have 46 lines. Do you have that function?

**Comment by jsmerel** [comment]
hmm, yeah I agree.  I don't see a line 46.  I checked older versions on my
computer and I also don't see a variant that has a relevant line 46.  I
guess she needs to send you her code, or do a clean re-download, right?

**Comment by vd2309** [comment]
Thanks!
I will do that - i copied and pasted so probably i missed a line or something - i will get back to you when I run it again.
