### ISSUE TITLE
Cannot run wrapper

### ISSUE THREAD

**Issue by yian-yin** [epnev/continuous_time_ca_sampler#9]
Hi there,

I was trying to implement this but cannot run wrapper.m, which shows

"Initializing using noise constrained FOOPSI...  Struct contents reference from a non-struct array object.

Error in cvxprob (line 48)
    selected = cvx___.solvers.selected;

Error in cvx_begin (line 41)
assignin( 'caller', 'cvx_problem', cvxprob( varargin{:} ) );

Error in cvx_foopsi (line 20)
    cvx_begin quiet

Error in constrained_foopsi (line 178)
                [c(:,rep),bas(rep),cin(rep)] = cvx_foopsi(y,b,c1,sn,b_lb,g,w_,~mis_data);

Error in get_initial_sample (line 20)
    [c,b,c1,g,sn,sp] =
    constrained_foopsi(Y,params.b,params.c1,params.g,params.sn,options);

Error in cont_ca_sampler (line 123)
   params.init = get_initial_sample(Y,params);

Error in wrapper (line 12)
SAMP = cont_ca_sampler(Y,params);"

Anyone have some idea what's happening? Thanks a lot!

**Comment by epnev** [comment]
@yian-yin 
Hi, have you installed cvx properly, i.e., run cvx_setup from inside the cxv folder after downloading it so all the routines are loaded? Check this for more info: http://cvxr.com/cvx/doc/install.html

**Comment by yian-yin** [comment]
It works well after I installed cvx, thanks a lot!

On May 14, 2018, at 2:51 PM, eftychios pnevmatikakis <notifications@github.com<mailto:notifications@github.com>> wrote:


@yian-yin<https://github.com/yian-yin>
Hi, have you installed cvx properly, i.e., run cvx_setup from inside the cxv folder after downloading it so all the routines are loaded? Check this for more info: http://cvxr.com/cvx/doc/install.html
